Tencent/feflow

lib/core/upgrade.js, lib/internal/build/builder.js, lib/internal/generator/generator.js, lib/internal/install/plugin.js
=> fix: fix cod to code

test/package.json, test/scripts/core/feflow-container/container/package.json, test/scripts/core/feflow-container/package.json, test/scripts/core/feflow.js, test/scripts/core/index.js, test/scripts/core/initClient.js, test/scripts/core/loadPlugins.js, test/scripts/core/logger.js, test/scripts/core/plugins/feflow-plugin-demo1/lib/index.js, test/scripts/core/plugins/feflow-plugin-demo1/package.json, test/scripts/core/plugins/feflow-plugin-demo2/lib/index.js, test/scripts/core/plugins/feflow-plugin-demo2/package.json, test/scripts/internal/install/index.js, test/scripts/utils/date.js, test/scripts/utils/index.js, test/scripts/utils/pkgJson.js
eslint codecov from 66% to 84%
=> add eslint codecov

CHANGELOG.md
=> docs(changelog): update v0.15.1 changelog

lib/core/index.js
=> fix: fix Loadind_require_error

test/scripts/core/initClient.js, test/scripts/core/loadPlugins.js, test/scripts/utils/pkgJson.js
=> chore: add test code

lib/core/upgrade.js, lib/feflow.js, lib/utils/func.js, lib/utils/index.js, lib/utils/util.js
=> fix: stop update when full update error

lib/core/command.js
=> fix: filter wrong command

lib/core/index.js, lib/internal/create/create.js, lib/internal/create/index.js
=> feat: support active subgenerator

src/cli/index.ts, src/core/index.ts, src/core/native/config.ts
releated issues: 
https://github.com/Tencent/feflow/issues/124
=> feat: support config client through feflow command

.gitignore, packages/feflow-report/README.md, packages/feflow-report/__tests__/index.spec.ts, packages/feflow-report/__tests__/objectFactory.spec.ts, packages/feflow-report/package.json, packages/feflow-report/src/api/config.ts, packages/feflow-report/src/api/index.ts, packages/feflow-report/src/common/objectFactory.ts, packages/feflow-report/src/common/utils.ts, packages/feflow-report/src/dev.ts, packages/feflow-report/src/index.ts, packages/feflow-report/tsconfig.json
=> chore: add feflow-report repo

packages/feflow-cli/package.json, packages/feflow-cli/src/cli/index.ts, packages/feflow-report/src/api/config.ts, packages/feflow-report/src/api/index.ts, packages/feflow-report/src/index.ts
refactor: remove useless branch and code
feat: feflow report
=> feat: report commands before execute

packages/feflow-cli/package.json, packages/feflow-report/package.json
chore: change report log to debug level
=> chore: change report log to debug level

package.json
chore: update feflow-report version
=> chore: update feflow-report version

packages/feflow-report/package.json, packages/feflow-report/src/api/index.ts
fix: support windows report with proxy
=> fix: support windows report with proxy

.gitignore, packages/feflow-cli/src/core/devkit/loadDevkits.ts
=> feat(devkit): support multiple builders.

lib/internal/lint/linter.js
=> fix: fix lint

lib/internal/lint/linter.js
1. fix eslint can not filter R type diff
2. add eslint files existence check
=> fix: eslint can not filter R type diff

packages/feflow-cli/src/core/index.ts
=> fix: local develop a scallfold cause upgrade check

packages/feflow-cli/src/core/plugin/loadUniversalPlugin.ts, packages/feflow-cli/src/shared/constant.ts, packages/feflow-cli/types/index.d.ts
feat(universal_plugin): replace execa to cross-spawn
=> Feat universal plugin

packages/feflow-cli/package.json, packages/feflow-cli/src/core/linker/index.ts, packages/feflow-cli/src/core/native/install.ts, packages/feflow-cli/src/core/plugin/loadUniversalPlugin.ts, packages/feflow-cli/src/core/schema/base.ts, packages/feflow-cli/src/core/schema/command.ts, packages/feflow-cli/src/core/schema/dependencies.ts, packages/feflow-cli/src/core/schema/plugin.ts, packages/feflow-cli/src/shared/constant.ts
1. check the plugin.yml syntax and check for compliance with dependencies
2. installed as the system command
3. support for extensible global variables
=> feat: installed as the system command and supports hooks

packages/feflow-cli/src/core/universal-pkg/schema/command.ts
=> fix: command run error

packages/feflow-cli/src/core/native/install.ts, packages/feflow-cli/src/core/plugin/loadUniversalPlugin.ts, packages/feflow-cli/src/core/universal-pkg/binp/index.ts, packages/feflow-cli/src/core/universal-pkg/schema/command.ts
1. 修复unixLink使用非正常终端路径时，注入path失效的问题
2. 子插件被调用允许触发父插件的更新
3. 子插件被父插件调用时使用静默模式，以避免fef自身的输出干扰插件间的信息交互。
=> Feat dep version

packages/feflow-cli/src/core/native/install.ts, packages/feflow-cli/src/core/universal-pkg/repository/git.ts
=> fix: upgrade circularly

packages/feflow-cli/src/core/native/list.ts
when use feflow list, it will show pkg's name and version(real installed version).
=> feat: fef list will show pkg name and version

packages/feflow-cli/src/core/native/install.ts, packages/feflow-cli/src/core/universal-pkg/repository/git.ts
=> Fix upgrade

packages/feflow-cli/src/core/index.ts, packages/feflow-cli/src/core/universal-pkg/binp/index.ts
=> feat: register bin path to all terminal

packages/feflow-cli/src/core/plugin/loadUniversalPlugin.ts
=> fix: exit when error

packages/feflow-cli/src/core/universal-pkg/repository/git.ts
=> fix: fetch tags fail

packages/feflow-cli/src/core/native/list.ts, packages/feflow-cli/src/core/native/upgrade.ts
when use fef upgrade you can update fef's latest version
=> feat: add upgrade command

packages/feflow-cli/src/core/plugin/loadUniversalPlugin.ts
=> Fix arg pass

packages/feflow-cli/src/core/native/install.ts, packages/feflow-cli/src/core/plugin/loadUniversalPlugin.ts
=> fix: install npm package

packages/feflow-cli/src/core/logger/index.ts, packages/feflow-cli/src/core/logger/report.ts, packages/feflow-cli/src/core/native/logger.ts
=> Sourceliu 20200806 logger

packages/feflow-cli/src/core/index.ts, packages/feflow-cli/src/core/logger/index.ts, packages/feflow-cli/src/core/logger/report.ts
=> fix: 获取插件名称

packages/feflow-cli/src/cli/index.ts
=> fix: add promiseRejection catch

packages/feflow-cli/src/cli/index.ts
when in debug mode, print error msg
=> fix: show err detail when in debug mode

packages/feflow-cli/src/core/native/install.ts, packages/feflow-cli/src/core/universal-pkg/linker/index.ts, packages/feflow-cli/src/core/universal-pkg/schema/plugin.ts
=> 协议增加runtime字段,用于描述运行时,并绕过feflow代理运行

packages/feflow-cli/src/core/native/install.ts, packages/feflow-report/src/common/utils.ts
1. 插件市场未找到内容是提示用户未找到
2. windows下查找git命令修复
=> fix: log err when not found plugin && fix command when in windows

packages/feflow-cli/src/core/resident/index.ts, packages/feflow-cli/src/core/resident/update.ts, packages/feflow-cli/src/core/resident/updateBeat.ts
=> fix: 修复多语言插件更新失败的问题

packages/feflow-cli/.keys, packages/feflow-cli/package.json, packages/feflow-cli/src/core/command-picker/index.ts, packages/feflow-cli/src/core/devkit/loadDevkits.ts, packages/feflow-cli/src/core/index.ts, packages/feflow-cli/src/core/logger/index.ts, packages/feflow-cli/src/core/logger/report.ts, packages/feflow-cli/src/core/native/install.ts, packages/feflow-cli/src/core/native/list.ts, packages/feflow-cli/src/core/plugin/applyPlugins.ts, packages/feflow-cli/src/core/universal-pkg/binp/index.ts, packages/feflow-cli/src/core/universal-pkg/dep/base.ts, packages/feflow-cli/src/core/universal-pkg/dep/pkg.ts, packages/feflow-cli/src/core/universal-pkg/persistence/install.ts, packages/feflow-cli/src/core/universal-pkg/repository/git.ts, packages/feflow-cli/src/core/universal-pkg/schema/plugin.ts, packages/feflow-cli/src/shared/constant.ts, packages/feflow-cli/src/shared/file.ts, packages/feflow-cli/src/shared/fs.ts, packages/feflow-cli/src/shared/git.ts, packages/feflow-cli/src/shared/npm.ts, packages/feflow-cli/src/shared/url.ts, packages/feflow-cli/src/shared/yaml.ts, packages/feflow-packager/package.json, packages/feflow-plugin-devtool/package.json, packages/feflow-report/package.json
=> Feat report log

packages/feflow-cli/src/core/commander/index.ts, packages/feflow-cli/src/core/index.ts, packages/feflow-cli/src/core/native/install.ts
1. package.json为空
2. 安装多语言插件异常code 127
=> Fix no package

packages/feflow-cli/package.json, packages/feflow-cli/src/core/native/init.ts
=> feat: 减化 fef 命令，提高用户使用率

packages/feflow-cli/src/core/command-picker/index.ts, packages/feflow-cli/src/core/native/install.ts, packages/feflow-cli/src/core/native/list.ts, packages/feflow-cli/src/shared/git.ts, packages/feflow-cli/src/shared/url.ts
1. 优化本地安装和GIT安装场景：支持windows，修复在unix-like下因为 冒号 导致PATH失效的问题
2. 修复命令缓存在多版本切换时异常的问题
3. 修复安装GIT时，url为ssh形式无法正常安装的问题
4. 兼容git clone时，对中文版本隐藏多余信息失效的问题
5. 修复A -> B，B -> A这种循环依赖无法自解的问题
6. 修复post-uninstall时机前置的问题
=> fix: 支持windows安装文件夹和git，修复命令缓存多版本切换的问题

packages/feflow-report/src/common/utils.ts, packages/feflow-report/src/report.ts
=> feat: 上报新增 node_version 字段

packages/feflow-cli/src/core/resident/index.ts
feat: heart-beat.json内容不合法时启动心跳进程
--story=20220810
=> Fix 20220722 window heart beat
